<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FaissNET.Cpu\Faiss.Cpu.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
      <PackageReference Include="xunit.v3" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\FaissNET.Cpu\Faiss.Cpu.csproj" />

        <ProjectReference Include="..\..\src\FaissNET.Native\Faiss.Native.csproj" />
    </ItemGroup>
</Project>
