<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <IncludeBuildOutput>false</IncludeBuildOutput>

        <NoWarn>$(NoWarn);NU5128</NoWarn>

        <PackageId>Faiss.NET.Gpu.Cuda</PackageId>
        <Version>1.0.0-preview.1</Version>
        <Authors>Binozo</Authors>
        <Description>Meta-package for NVIDIA GPUs.</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FaissNET.Gpu\Faiss.Gpu.csproj" />
        <ProjectReference Include="..\FaissNET.Linux.Gpu.Cuda\Faiss.Linux.Gpu.Cuda.csproj" />
    </ItemGroup>

</Project>