<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <NoWarn>$(NoWarn);NU5128</NoWarn>
        <IncludeBuildOutput>false</IncludeBuildOutput>

        <PackageId>Faiss.NET.Native.Linux</PackageId>
        <Version>1.0.0-preview.4</Version>
        <Authors>Binozo</Authors>
        <Description>Native Linux (x64 and arm64) binaries for Faiss.NET.</Description>
        <PackageTags>faiss vector search similarity-search machine-learning ai knn hnsw embeddings linux x64 arm64</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Copyright>Copyright (c) 2026 Noah Czaplewski</Copyright>

        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/Binozo/Faiss.NET</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://github.com/Binozo/Faiss.NET</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
        <None Include="..\..\LICENSE" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FaissNET.Cpu\Faiss.Cpu.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="runtimes\linux-x64\native\*.so"
              Pack="true"
              PackagePath="runtimes\linux-x64\native\" />

        <None Include="runtimes\linux-arm64\native\*.so"
              Pack="true"
              PackagePath="runtimes\linux-arm64\native\" />
    </ItemGroup>

    <ItemGroup Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64'">
        <ContentWithTargetPath Include="runtimes\linux-x64\native\*.so"
                               TargetPath="%(Filename)%(Extension)"
                               CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'Arm64'">
        <ContentWithTargetPath Include="runtimes\linux-arm64\native\*.so"
                               TargetPath="%(Filename)%(Extension)"
                               CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>