name: Build and Package Faiss MacOS

on:
  push:
    branches: [ main ]
    paths:
      - "faiss"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: arm64
            runner: macos-26
            opt_level: sve
          - arch: x64
            runner: macos-26-intel
            opt_level: avx2
    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Build Dependencies
      run: |
        brew install libomp

    - name: Configure Faiss
      working-directory: faiss
      run: |
        LIBOMP_PATH=$(brew --prefix libomp)

        cmake -B build . \
          -DFAISS_ENABLE_C_API=ON \
          -DBUILD_SHARED_LIBS=ON \
          -DFAISS_ENABLE_GPU=OFF \
          -DFAISS_OPT_LEVEL=${{ matrix.opt_level }} \
          -DFAISS_ENABLE_MKL=OFF \
          -DCMAKE_CXX_FLAGS="-I$LIBOMP_PATH/include" \
          -DOpenMP_ROOT=$LIBOMP_PATH \
          -DFAISS_ENABLE_PYTHON=OFF \
          -DBUILD_TESTING=OFF \
          -DFAISS_ENABLE_EXTRAS=OFF \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
          -DCMAKE_INSTALL_RPATH='$ORIGIN'

    - name: Build Faiss C API
      working-directory: faiss
      run: |
        cmake --build build --config Release --target faiss_c

    - name: Prepare artifacts
      run: |
        mkdir -p artifacts
        cp faiss/build/c_api/libfaiss_c.dylib artifacts/
        cp faiss/build/faiss/libfaiss.dylib artifacts/

    - name: Upload Zip Artifact
      uses: actions/upload-artifact@v4
      with:
        compression-level: '9'
        name: faiss-macos-${{ matrix.arch }}-binaries.zip
        path: artifacts/*

  build-pack:
    needs: [build]
    runs-on: ubuntu-24.04
    
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download x64 Artifacts
        uses: actions/download-artifact@v8
        with:
          name: faiss-macos-x64-binaries.zip
          path: x64

      - name: Download ARM64 Artifacts
        uses: actions/download-artifact@v8
        with:
          name: faiss-macos-arm64-binaries.zip
          path: arm64

      - name: Prepare Native Runtimes
        run: |
          cp x64/* src/FaissNET.MacOS/runtimes/macos-x64/native/
          cp arm64/* src/FaissNET.MacOS/runtimes/macos-arm64/native/

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Pack NuGet Package
        run: |
          dotnet pack src/FaissNET.MacOS/Faiss.MacOS.csproj -c Release -o ./nupkg

      - name: Upload NuGet Package
        uses: actions/upload-artifact@v4
        with:
          name: faiss-macos-nupkg.zip
          path: 'nupkg/*.nupkg'